forecast_response = {
    "cod": "200",
    "message": 0,
    "cnt": 40,
    "list": [
        {
            "dt": 1673330400,
            "main": {
                "temp": 29.69,
                "feels_like": 28.94,
                "temp_min": 28.17,
                "temp_max": 29.69,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1003,
                "humidity": 36,
                "temp_kf": 1.52,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 4.9, "deg": 226, "gust": 4.94},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-10 06:00:00",
        },
        {
            "dt": 1673341200,
            "main": {
                "temp": 26.58,
                "feels_like": 26.58,
                "temp_min": 24.65,
                "temp_max": 26.58,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 39,
                "temp_kf": 1.93,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 42},
            "wind": {"speed": 4.34, "deg": 165, "gust": 6.8},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-10 09:00:00",
        },
        {
            "dt": 1673352000,
            "main": {
                "temp": 18.35,
                "feels_like": 17.81,
                "temp_min": 18.35,
                "temp_max": 18.35,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1005,
                "humidity": 60,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 65},
            "wind": {"speed": 3.15, "deg": 138, "gust": 4.11},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-10 12:00:00",
        },
        {
            "dt": 1673362800,
            "main": {
                "temp": 18.21,
                "feels_like": 17.44,
                "temp_min": 18.21,
                "temp_max": 18.21,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 52,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 91},
            "wind": {"speed": 2.15, "deg": 119, "gust": 2.33},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-10 15:00:00",
        },
        {
            "dt": 1673373600,
            "main": {
                "temp": 18.81,
                "feels_like": 17.79,
                "temp_min": 18.81,
                "temp_max": 18.81,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1003,
                "humidity": 40,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 81},
            "wind": {"speed": 1.37, "deg": 121, "gust": 1.46},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-10 18:00:00",
        },
        {
            "dt": 1673384400,
            "main": {
                "temp": 21.63,
                "feels_like": 20.66,
                "temp_min": 21.63,
                "temp_max": 21.63,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 31,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 32},
            "wind": {"speed": 1.4, "deg": 48, "gust": 1.82},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-10 21:00:00",
        },
        {
            "dt": 1673395200,
            "main": {
                "temp": 26.48,
                "feels_like": 26.48,
                "temp_min": 26.48,
                "temp_max": 26.48,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 26,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 63},
            "wind": {"speed": 2.56, "deg": 253, "gust": 2.32},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-11 00:00:00",
        },
        {
            "dt": 1673406000,
            "main": {
                "temp": 28.29,
                "feels_like": 27.17,
                "temp_min": 28.29,
                "temp_max": 28.29,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1004,
                "humidity": 27,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 3.56, "deg": 244, "gust": 3.82},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-11 03:00:00",
        },
        {
            "dt": 1673416800,
            "main": {
                "temp": 28.75,
                "feels_like": 27.52,
                "temp_min": 28.75,
                "temp_max": 28.75,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 1003,
                "humidity": 27,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.24, "deg": 227, "gust": 4.84},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-11 06:00:00",
        },
        {
            "dt": 1673427600,
            "main": {
                "temp": 26.36,
                "feels_like": 26.36,
                "temp_min": 26.36,
                "temp_max": 26.36,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1004,
                "humidity": 39,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 87},
            "wind": {"speed": 3.9, "deg": 180, "gust": 5.9},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-11 09:00:00",
        },
        {
            "dt": 1673438400,
            "main": {
                "temp": 20.78,
                "feels_like": 20.22,
                "temp_min": 20.78,
                "temp_max": 20.78,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1005,
                "humidity": 50,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 47},
            "wind": {"speed": 3.41, "deg": 140, "gust": 5.1},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-11 12:00:00",
        },
        {
            "dt": 1673449200,
            "main": {
                "temp": 19.72,
                "feels_like": 19.03,
                "temp_min": 19.72,
                "temp_max": 19.72,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1005,
                "humidity": 49,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 6},
            "wind": {"speed": 2.2, "deg": 121, "gust": 2.61},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-11 15:00:00",
        },
        {
            "dt": 1673460000,
            "main": {
                "temp": 19.35,
                "feels_like": 18.59,
                "temp_min": 19.35,
                "temp_max": 19.35,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 48,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 5},
            "wind": {"speed": 1.99, "deg": 114, "gust": 2.03},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-11 18:00:00",
        },
        {
            "dt": 1673470800,
            "main": {
                "temp": 21.68,
                "feels_like": 20.92,
                "temp_min": 21.68,
                "temp_max": 21.68,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1006,
                "humidity": 39,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 2},
            "wind": {"speed": 1.79, "deg": 110, "gust": 2.2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-11 21:00:00",
        },
        {
            "dt": 1673481600,
            "main": {
                "temp": 29.13,
                "feels_like": 27.73,
                "temp_min": 29.13,
                "temp_max": 29.13,
                "pressure": 1013,
                "sea_level": 1013,
                "grnd_level": 1006,
                "humidity": 25,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 1},
            "wind": {"speed": 1.35, "deg": 229, "gust": 1.24},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-12 00:00:00",
        },
        {
            "dt": 1673492400,
            "main": {
                "temp": 30.53,
                "feels_like": 29.18,
                "temp_min": 30.53,
                "temp_max": 30.53,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1005,
                "humidity": 29,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 3.55, "deg": 241, "gust": 3.33},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-12 03:00:00",
        },
        {
            "dt": 1673503200,
            "main": {
                "temp": 30.69,
                "feels_like": 29.7,
                "temp_min": 30.69,
                "temp_max": 30.69,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1004,
                "humidity": 33,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 2},
            "wind": {"speed": 4.75, "deg": 211, "gust": 5.69},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-12 06:00:00",
        },
        {
            "dt": 1673514000,
            "main": {
                "temp": 29.11,
                "feels_like": 27.8,
                "temp_min": 29.11,
                "temp_max": 29.11,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 27,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 7},
            "wind": {"speed": 5.06, "deg": 143, "gust": 7.72},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-12 09:00:00",
        },
        {
            "dt": 1673524800,
            "main": {
                "temp": 23.96,
                "feels_like": 23.17,
                "temp_min": 23.96,
                "temp_max": 23.96,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1005,
                "humidity": 29,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 5},
            "wind": {"speed": 3.56, "deg": 129, "gust": 7.62},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-12 12:00:00",
        },
        {
            "dt": 1673535600,
            "main": {
                "temp": 22.58,
                "feels_like": 21.7,
                "temp_min": 22.58,
                "temp_max": 22.58,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1005,
                "humidity": 31,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 0},
            "wind": {"speed": 1.99, "deg": 142, "gust": 3.1},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-12 15:00:00",
        },
        {
            "dt": 1673546400,
            "main": {
                "temp": 22.9,
                "feels_like": 21.92,
                "temp_min": 22.9,
                "temp_max": 22.9,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 26,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 4},
            "wind": {"speed": 2.21, "deg": 75, "gust": 2.19},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-12 18:00:00",
        },
        {
            "dt": 1673557200,
            "main": {
                "temp": 24.72,
                "feels_like": 24.08,
                "temp_min": 24.72,
                "temp_max": 24.72,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1005,
                "humidity": 32,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 6},
            "wind": {"speed": 0.97, "deg": 104, "gust": 1.41},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-12 21:00:00",
        },
        {
            "dt": 1673568000,
            "main": {
                "temp": 30.22,
                "feels_like": 28.58,
                "temp_min": 30.22,
                "temp_max": 30.22,
                "pressure": 1012,
                "sea_level": 1012,
                "grnd_level": 1005,
                "humidity": 24,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 47},
            "wind": {"speed": 0.87, "deg": 261, "gust": 2.4},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-13 00:00:00",
        },
        {
            "dt": 1673578800,
            "main": {
                "temp": 32.82,
                "feels_like": 30.99,
                "temp_min": 32.82,
                "temp_max": 32.82,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 23,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 67},
            "wind": {"speed": 3.81, "deg": 259, "gust": 4.16},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-13 03:00:00",
        },
        {
            "dt": 1673589600,
            "main": {
                "temp": 33.04,
                "feels_like": 31.53,
                "temp_min": 33.04,
                "temp_max": 33.04,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 1003,
                "humidity": 26,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 38},
            "wind": {"speed": 3.26, "deg": 233, "gust": 4.1},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-13 06:00:00",
        },
        {
            "dt": 1673600400,
            "main": {
                "temp": 31.96,
                "feels_like": 30.55,
                "temp_min": 31.96,
                "temp_max": 31.96,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 1002,
                "humidity": 28,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 4},
            "wind": {"speed": 4.05, "deg": 172, "gust": 6.11},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-13 09:00:00",
        },
        {
            "dt": 1673611200,
            "main": {
                "temp": 26.12,
                "feels_like": 26.12,
                "temp_min": 26.12,
                "temp_max": 26.12,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1003,
                "humidity": 34,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01n"}
            ],
            "clouds": {"all": 4},
            "wind": {"speed": 3.07, "deg": 124, "gust": 4.92},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-13 12:00:00",
        },
        {
            "dt": 1673622000,
            "main": {
                "temp": 25.75,
                "feels_like": 25.24,
                "temp_min": 25.75,
                "temp_max": 25.75,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1003,
                "humidity": 33,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 31},
            "wind": {"speed": 1.79, "deg": 93, "gust": 2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-13 15:00:00",
        },
        {
            "dt": 1673632800,
            "main": {
                "temp": 25.87,
                "feels_like": 25.37,
                "temp_min": 25.87,
                "temp_max": 25.87,
                "pressure": 1009,
                "sea_level": 1009,
                "grnd_level": 1002,
                "humidity": 33,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 42},
            "wind": {"speed": 1.72, "deg": 89, "gust": 1.73},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-13 18:00:00",
        },
        {
            "dt": 1673643600,
            "main": {
                "temp": 26.51,
                "feels_like": 26.51,
                "temp_min": 26.51,
                "temp_max": 26.51,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1003,
                "humidity": 33,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 63},
            "wind": {"speed": 1.82, "deg": 163, "gust": 2.25},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-13 21:00:00",
        },
        {
            "dt": 1673654400,
            "main": {
                "temp": 31.61,
                "feels_like": 30.28,
                "temp_min": 31.61,
                "temp_max": 31.61,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1003,
                "humidity": 29,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 53},
            "wind": {"speed": 2.83, "deg": 267, "gust": 4.41},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-14 00:00:00",
        },
        {
            "dt": 1673665200,
            "main": {
                "temp": 31.43,
                "feels_like": 30.29,
                "temp_min": 31.43,
                "temp_max": 31.43,
                "pressure": 1010,
                "sea_level": 1010,
                "grnd_level": 1004,
                "humidity": 31,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 803,
                    "main": "Clouds",
                    "description": "broken clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 62},
            "wind": {"speed": 5.21, "deg": 214, "gust": 6.35},
            "visibility": 10000,
            "pop": 0.04,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-14 03:00:00",
        },
        {
            "dt": 1673676000,
            "main": {
                "temp": 28.36,
                "feels_like": 27.71,
                "temp_min": 28.36,
                "temp_max": 28.36,
                "pressure": 1011,
                "sea_level": 1011,
                "grnd_level": 1004,
                "humidity": 36,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03d",
                }
            ],
            "clouds": {"all": 39},
            "wind": {"speed": 10.01, "deg": 192, "gust": 11.13},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-14 06:00:00",
        },
        {
            "dt": 1673686800,
            "main": {
                "temp": 21.78,
                "feels_like": 21.4,
                "temp_min": 21.78,
                "temp_max": 21.78,
                "pressure": 1015,
                "sea_level": 1015,
                "grnd_level": 1008,
                "humidity": 53,
                "temp_kf": 0,
            },
            "weather": [
                {"id": 800, "main": "Clear", "description": "clear sky", "icon": "01d"}
            ],
            "clouds": {"all": 8},
            "wind": {"speed": 6.55, "deg": 164, "gust": 11.21},
            "visibility": 10000,
            "pop": 0.02,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-14 09:00:00",
        },
        {
            "dt": 1673697600,
            "main": {
                "temp": 17.63,
                "feels_like": 17.35,
                "temp_min": 17.63,
                "temp_max": 17.63,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 1011,
                "humidity": 73,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 802,
                    "main": "Clouds",
                    "description": "scattered clouds",
                    "icon": "03n",
                }
            ],
            "clouds": {"all": 44},
            "wind": {"speed": 7.09, "deg": 169, "gust": 12.41},
            "visibility": 10000,
            "pop": 0.02,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-14 12:00:00",
        },
        {
            "dt": 1673708400,
            "main": {
                "temp": 17.75,
                "feels_like": 17.62,
                "temp_min": 17.75,
                "temp_max": 17.75,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 1011,
                "humidity": 78,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 97},
            "wind": {"speed": 6.34, "deg": 148, "gust": 10.59},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-14 15:00:00",
        },
        {
            "dt": 1673719200,
            "main": {
                "temp": 17.04,
                "feels_like": 16.81,
                "temp_min": 17.04,
                "temp_max": 17.04,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 1011,
                "humidity": 77,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04n",
                }
            ],
            "clouds": {"all": 99},
            "wind": {"speed": 5.78, "deg": 146, "gust": 9.2},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "n"},
            "dt_txt": "2023-01-14 18:00:00",
        },
        {
            "dt": 1673730000,
            "main": {
                "temp": 16.57,
                "feels_like": 16.16,
                "temp_min": 16.57,
                "temp_max": 16.57,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 1011,
                "humidity": 72,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 6.7, "deg": 143, "gust": 10.79},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-14 21:00:00",
        },
        {
            "dt": 1673740800,
            "main": {
                "temp": 18.42,
                "feels_like": 17.81,
                "temp_min": 18.42,
                "temp_max": 18.42,
                "pressure": 1020,
                "sea_level": 1020,
                "grnd_level": 1013,
                "humidity": 57,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.76, "deg": 137, "gust": 6.72},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-15 00:00:00",
        },
        {
            "dt": 1673751600,
            "main": {
                "temp": 21.9,
                "feels_like": 21.29,
                "temp_min": 21.9,
                "temp_max": 21.9,
                "pressure": 1018,
                "sea_level": 1018,
                "grnd_level": 1011,
                "humidity": 44,
                "temp_kf": 0,
            },
            "weather": [
                {
                    "id": 804,
                    "main": "Clouds",
                    "description": "overcast clouds",
                    "icon": "04d",
                }
            ],
            "clouds": {"all": 100},
            "wind": {"speed": 4.78, "deg": 159, "gust": 5.35},
            "visibility": 10000,
            "pop": 0,
            "sys": {"pod": "d"},
            "dt_txt": "2023-01-15 03:00:00",
        },
    ],
    "city": {
        "id": 2078025,
        "name": "Adelaide",
        "coord": {"lat": -34.9287, "lon": 138.5986},
        "country": "AU",
        "population": 1074159,
        "timezone": 37800,
        "sunrise": 1673293336,
        "sunset": 1673344974,
    },
}
